import type { Metadata } from "next";
import { El_Messiri, Inter } from "next/font/google";
import "./globals.css";
import ContactModal from "@/components/ui/ContactModal";
import { Suspense } from "react";
import { Analytics } from "@vercel/analytics/react";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });
const el_messiri = El_Messiri({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Mahmoud Ahmed's Portofolio",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${locale == "en" ? inter.className : el_messiri.className} dark`}>
        <NextIntlClientProvider messages={messages}>
          <Suspense>
            <ContactModal />
          </Suspense>
          <div className="mx-auto max-w-7xl px-5 sm:px-10" dir={locale == "en" ? "ltr" : "rtl"}>{children}</div>
        </NextIntlClientProvider>
        <Analytics />
      </body>
    </html>
  );
}
