import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContactModal from "@/components/ui/ContactModal";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mahmoud Ahmed's Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " dark"}>
        <Suspense>
          <ContactModal />
        </Suspense>
        <div className="mx-auto max-w-7xl px-5 sm:px-10">{children}</div>
      </body>
    </html>
  );
}
